import Head from '@/app/head'
import './globals.css'
import NavBar from '@/app/components/nav-bar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head />
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
